<a href="https://colab.research.google.com/github/IgorTTenorio/ai-python-playground/blob/main/ai_python_challenge3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Desafio 3:
1. Carregar um arquivo .csv com feedback de clientes (reviews.csv)
2. Usar um LLM para classificar o sentimento de cada feedback (Positivo, Negativo, Neutro)
3. Adicionar uma nessa classificacao no Dataframe

In [5]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.7/141.7 kB 10.5 MB/s eta 0:00:00

In [1]:
import pandas as pd
df = pd.read_csv("/content/reviews.csv")

In [3]:
import os
from google.colab import userdata
os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

In [6]:
from groq import Groq

client = Groq()

In [13]:
reviews = df['reviewText']

0     it works as expected. I should have sprung for...
1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
5     It works, but file writes are a bit slower tha...
6     I bought 2 of those SanDisk 32 GB microSD , us...
7     The memory card is an excellent condition and ...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
12    everything about it was great, except for the ...
13    Used in my phone it's plenty fast and works ju...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
16    good card. work as describes. haven't had any ...
17    I got this because I just couldn't pass up the...
18    It works but the actual R/W speeds are 18/8 MB...
19    Does it's job and fairly cheap for what it's w...
20    Still don't feel is very fast or is just my ph...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
28    The package arrived on time, it's very well pa...
29    Does what it says. Hasn't broken yet, and I ho...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
32    I have two of these and use them for my Galazy...
33    I join the long list of customers who have had...
34    I do not get the advertised speed of 30MB/s, m...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
37    Reliable and inexpensive. However, it's quite ...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

In [11]:
def classificador_de_reviews(reviews):
  respostas = []
  for review in reviews:
    resposta = ""
    completion = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
          {
            "role": "user",
            "content": f'Classifique o seguinte texto de revisao como Positivo, Negativo ou Neutro: {review}'
          }
        ],
        temperature=1,
        max_completion_tokens=8192,
        top_p=1,
        reasoning_effort="medium",
        stream=True,
        stop=None
    )
    for chunk in completion:
      content = chunk.choices[0].delta.content
      if content:
          resposta += content
    respostas.append(resposta)
  return respostas

In [16]:
reviews_classificadas = classificador_de_reviews(reviews)

In [23]:
df["sentimento"] = reviews_classificadas

In [25]:
reviews2 = df[["reviewText","sentimento"]]
reviews2

                                           reviewText sentimento
0   it works as expected. I should have sprung for...   Negativo
1   This think has worked out great.Had a diff. br...   Positivo
2   Bought it with Retail Packaging, arrived legit...   Positivo
3   It's mini storage.  It doesn't do anything els...   Positivo
4   I have it in my phone and it never skips a bea...   Positivo
5   It works, but file writes are a bit slower tha...   Negativo
6   I bought 2 of those SanDisk 32 GB microSD , us...   Negativo
7   The memory card is an excellent condition and ...   Positivo
8   I bougth this micro SD card after some trubles...   Negativo
9   Ordered this for a Galaxy S3.  Lasted a few mo...   Negativo
10  more like 8mb/s in my Note 10.1 and that's usi...     Neutro
11  I used this for a few months in my phone, then...   Negativo
12  everything about it was great, except for the ...   Positivo
13  Used in my phone it's plenty fast and works ju...   Positivo
14  This card advertises itself as UHS1 but it's a...   Negativo
15  I bought this SD card for my android phone thi...   Negativo
16  good card. work as describes. haven't had any ...   Positivo
17  I got this because I just couldn't pass up the...   Positivo
18  It works but the actual R/W speeds are 18/8 MB...   Negativo
19  Does it's job and fairly cheap for what it's w...     Neutro
20  Still don't feel is very fast or is just my ph...     Neutro
21  I bought 64GB version of the card to use with ...   Negativo
22  I have an old SanDisk SD card that still works...   Negativo
23  Used it in my Galaxy Note 2 for the past 16 mo...   Negativo
24  Worked great in my galaxy s4--until it didn't ...   Negativo
25  I bought this on August of 2013.  As of April ...   Negativo
26  So this product is a large disappointment...bo...   Negativo
27  I will keep it short and sweet for potential b...   Negativo
28  The package arrived on time, it's very well pa...     Neutro
29  Does what it says. Hasn't broken yet, and I ho...   Positivo
30  Thus microSD card worked fine for a year in my...   Negativo
31  I think this is probably a fine product, but i...   Negativo
32  I have two of these and use them for my Galazy...   Positivo
33  I join the long list of customers who have had...     Neutro
34  I do not get the advertised speed of 30MB/s, m...     Neutro
35  the micro sd works great as described. but bew...   Negativo
36  than i expected. I don't know if it would kill...   Negativo
37  Reliable and inexpensive. However, it's quite ...     Neutro
38  I bought this primarily to use in my Surface P...   Negativo
39  I really don't know what to think about this I...   Negativo